version: "3.9"

services:
  db:
    container_name: mysql-db
    image: mysql:8
    platform: linux/amd64
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/init-sql:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    tty: true
    restart: always
volumes:
  db-store:
